In [2]:
import torch 
import models

script to sanity check reshaping processes within models

# UNet

In [8]:
unet = models.ClimSimUNet()

x = torch.arange(0, 45*2+4).unsqueeze(0)

print(x.shape)
print(x)

torch.Size([1, 94])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
         36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
         54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
         72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
         90, 91, 92, 93]])


In [12]:
y = unet._reshape_from_standard_format(x)

print(y.shape)
print(y[0, 0, :])
print(y[0, 1, :])
print(y[0, 2, :])
print(y[0, 3, :])



torch.Size([1, 6, 48])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44,  0,  0,  0])
tensor([45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62,
        63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
        81, 82, 83, 84, 85, 86, 87, 88, 89,  0,  0,  0])
tensor([90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90,
        90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90,
        90, 90, 90, 90, 90, 90, 90, 90, 90,  0,  0,  0])
tensor([91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91,
        91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91,
        91, 91, 91, 91, 91, 91, 91, 91, 91,  0,  0,  0])


In [23]:
r = torch.arange(0, 45*2+8).unsqueeze(0)

y1 = r[:, 0:45]
y2 = r[:, 45:90]
y3 = torch.ones(1, 45) * 90
y4 = torch.ones(1, 45) * 91
y5 = torch.ones(1, 45) * 92
y6 = torch.ones(1, 45) * 93
y7 = torch.ones(1, 45) * 94
y8 = torch.ones(1, 45) * 95
y9 = torch.ones(1, 45) * 96
y10 = torch.ones(1, 45) * 97

y = torch.stack([y1, y2, y3, y4, y5, y6, y7, y8, y9, y10]).transpose(1, 0)
print(y.shape)
# print(y)


torch.Size([1, 10, 45])


In [25]:
out = unet._reshape_to_standard_format(y)

print(out.shape)
print(out)

torch.Size([1, 98])
tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
         14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.,
         28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41.,
         42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52., 53., 54., 55.,
         56., 57., 58., 59., 60., 61., 62., 63., 64., 65., 66., 67., 68., 69.,
         70., 71., 72., 73., 74., 75., 76., 77., 78., 79., 80., 81., 82., 83.,
         84., 85., 86., 87., 88., 89., 90., 91., 92., 93., 94., 95., 96., 97.]])


# Squeezeformer

In [13]:

squeezeformer = models.SqueezeFormer(in_dim=6, embed_dim=64, head_dim=256, out_dim=10)

x = torch.arange(0, 45*2+4).unsqueeze(0)

print(x.shape)
print(x)

torch.Size([1, 94])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
         36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
         54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
         72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
         90, 91, 92, 93]])


In [15]:
y = squeezeformer._reshape_from_standard_format(x)

print(y.shape)
print(y[0, :, 0])
print(y[0, :, 1])
print(y[0, :, 2])
print(y[0, :, 3])


torch.Size([1, 45, 6])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44])
tensor([45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62,
        63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
        81, 82, 83, 84, 85, 86, 87, 88, 89])
tensor([90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90,
        90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90,
        90, 90, 90, 90, 90, 90, 90, 90, 90])
tensor([91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91,
        91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91,
        91, 91, 91, 91, 91, 91, 91, 91, 91])


In [29]:
r = torch.arange(0, 45*2+8).unsqueeze(0)

y1 = r[:, 0:45]
y2 = r[:, 45:90]
y3 = torch.ones(1, 45) * 90
y4 = torch.ones(1, 45) * 91
y5 = torch.ones(1, 45) * 92
y6 = torch.ones(1, 45) * 93
y7 = torch.ones(1, 45) * 94
y8 = torch.ones(1, 45) * 95
y9 = torch.ones(1, 45) * 96
y10 = torch.ones(1, 45) * 97

y = torch.stack([y1, y2, y3, y4, y5, y6, y7, y8, y9, y10]).permute(1, 2, 0)
print(y.shape)
# print(y)


torch.Size([1, 45, 10])


In [30]:
out = squeezeformer._reshape_to_standard_format(y)

print(out.shape)
print(out)

torch.Size([1, 98])
tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
         14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.,
         28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41.,
         42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52., 53., 54., 55.,
         56., 57., 58., 59., 60., 61., 62., 63., 64., 65., 66., 67., 68., 69.,
         70., 71., 72., 73., 74., 75., 76., 77., 78., 79., 80., 81., 82., 83.,
         84., 85., 86., 87., 88., 89., 90., 91., 92., 93., 94., 95., 96., 97.]])
